/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.sql.*;

public class MySQLExample {
    public static void doTest() {
        // 1. 添加 MySQL 连接驱动程序依赖
        // 例如使用 Maven 添加以下依赖:
        // <dependency>
        //     <groupId>mysql</groupId>
        //     <artifactId>mysql-connector-java</artifactId>
        //     <version>8.0.28</version>
        // </dependency>

        // 2. 建立数据库连接
        //String url = "jdbc:mysql://127.0.0.1:3306/mysql?useSSL=false";
        //String username = "root";
        //String password = "cknk4jnh";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // MySQL Connector/J 8.0及以上版本
            // 或者
            // Class.forName("com.mysql.jdbc.Driver"); // MySQL Connector/J 5.1.x版本
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("MySQL JDBC Driver not found,please try again..", e);
        }
        String username = System.getenv("username");
        String password = System.getenv("password");
        String hostname = System.getenv("hostname");
        String port = System.getenv("port");
        String url = "jdbc:mysql://"+hostname+":"+port+"/mysql?useSSL=false";

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connected to database!");
            // 3. 执行 SQL 查询
            String query = "SELECT * FROM user";
            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(query)) {

                // 4. 处理查询结果
                while (resultSet.next()) {
                    String host = resultSet.getString("Host");
                    String user = resultSet.getString("User");
                    System.out.println("Host: " + host + ", User: " + user);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

