/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.sql.*;

public class PostgreSQLExample {
    public static void doTest()  {
        // 1. 建立数据库连接
        //String url = "jdbc:postgresql://127.0.0.1:5432/postgres?useSSL=false";
        //String username = "postgres";
        //String password = "tps6stdr";

        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("PostgreSQL JDBC Driver not found，please.", e);
        }
        String username = System.getenv("username");
        String password = System.getenv("password");
        String hostname = System.getenv("host");
        String port = System.getenv("port");

        String url = "jdbc:postgresql://"+hostname+":"+port+"/postgres?useSSL=false";

        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connected to database!");

            // 2. 执行 SQL 查询
            String query = "SELECT * FROM pg_stat_activity";
            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(query)) {

                // 3. 处理查询结果
                while (resultSet.next()) {
		    String pid = resultSet.getString("Pid");
                    String usename = resultSet.getString("usename");
                    System.out.println("Pid: " + pid + ", Usename: " + usename);
                }
            }

	    connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

