/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.JedisSentinelPool;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.HostAndPort;

import java.util.HashSet;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class SentinelRedisExample {
    private static final Logger logger = LoggerFactory.getLogger(SentinelRedisExample.class);
    public static JedisSentinelPool createJedisSentinelPool() {
        String username = System.getenv("username");
        String password = System.getenv("password");
        String hostname = System.getenv("host");
        String port = System.getenv("port");
        String sentinelpwd = System.getenv("sentinelpwd");
        JedisPoolConfig poolConfig = new JedisPoolConfig();
        // 设置连接池配置,如最大连接数、最大空闲连接数等

        Set<String> sentinelSet = new HashSet<>();
        sentinelSet.add(new HostAndPort(hostname, Integer.parseInt(port)).toString());


        // master-name, sentinel-hosts, redis-password, sentinel-password
        return new JedisSentinelPool(hostname, sentinelSet,password,sentinelpwd);
    }

    public static void doTest() {
        JedisSentinelPool jedisSentinelPool = createJedisSentinelPool();

        try (Jedis jedis = jedisSentinelPool.getResource()) {
            jedis.set("corp", "ApeCloud");
            String value = jedis.get("corp");
            System.out.println("corp: " + value);
        }
    }
}

