name: Release Image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The tag name of image'
        required: true
        default: 'foundationdb'
      release_platform:
        description: 'The platform of release image'
        required: false
        default: 'linux/amd64'
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}


jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_release_version.outputs.release_version }}
      release-platform: ${{ steps.get_release_version.outputs.release_platform }}
    steps:
      - name: Get Release Version
        id: get_release_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT
          
          RELEASE_PLATFORM=${{ inputs.release_platform }}
          if [ -z "$RELEASE_PLATFORM" ]; then
              RELEASE_PLATFORM="linux/amd64,linux/arm64"
          fi
          echo release_platform="$RELEASE_PLATFORM" >> $GITHUB_OUTPUT

  release-image:
    permissions:
      id-token: write
      contents: read
    needs: [ release-version ]
    uses: apecloud-inc/apecloud-cd/.github/workflows/release-image-no-cache.yml@v0.7.0
    with:
      IMG: "apecloud/dbclient"
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      DOCKERFILE_PATH: "./docker/Dockerfile"
      APECD_REF: "v0.7.0"
      BUILDX_PLATFORMS: "${{ needs.release-version.outputs.release-platform }}"
    secrets: inherit

  release-image-latest:
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.action == 'published' }}
    needs: [ release-version ]
    uses: apecloud-inc/apecloud-cd/.github/workflows/release-image-no-cache.yml@v0.7.0
    with:
      IMG: "apecloud/dbclient"
      VERSION: "latest"
      DOCKERFILE_PATH: "./docker/Dockerfile"
      APECD_REF: "v0.7.0"
      BUILDX_PLATFORMS: "${{ needs.release-version.outputs.release-platform }}"
    secrets: inherit
